version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./knownProgrammer:/knownProgrammer
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    env_file:
      - knownProgrammer/.env
    restart: always
